name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container  # ✅ Ensure Buildx uses the correct driver
          driver-opts: network=host

      - name: Create and Use a Buildx Builder
        run: |
          docker buildx create --name mybuilder --use --driver docker-container
          docker buildx inspect --bootstrap

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker Image with Caching
        run: |
          docker buildx build --builder mybuilder \
                              --cache-from=type=local,src=/tmp/.buildx-cache \
                              --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
                              -t nova .

            
    #   - name: Run Tests Inside Docker
    #     run: |
    #      docker run --rm nova python manage.py test