name: CI Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Setup Docker
              uses: docker/setup-buildx-action@v2
              with:
                driver: docker-container

            - name: Cache Docker Layers
              uses: actions/cache@v3
              with:
                path: /tmp/.buildx-cache
                key: ${{ runner.os }}-buildx-${{ github.sha}}
                restore-keys: |
                    ${{ runner.os }}-buildx-
            
            - name: Install Docker Compose V2
              run: |
                mkdir -p $HOME/.docker/cli-plugins
                curl -SL https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-linux-x86_64 -o $HOME/.docker/cli-plugins/docker-compose
                chmod +x $HOME/.docker/cli-plugins/docker-compose
                docker version
                docker compose version

            - name: Build Docker Image
              run: |
                docker build --cache-from=type=local,src=/tmp/.buildx-cache \
                            --cache-to=type=local,dest=/tmp/.buildx-cache \
                            -t nova .
            
            - name: Run Tests Inside Docker
              run: |
                docker run --rm nova python manage.py test